CREATE TABLE IF NOT EXISTS tasks(
   id INT PRIMARY KEY,
   name VARCHAR (50) NOT NULL,
   target VARCHAR (80) NOT NULL,
   is_active BOOLEAN NOT NULL,
   test_id SMALLINT NOT NULL,
   test_payload JSONB NULL,
   created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION task_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER task_updated_at_trigger
BEFORE UPDATE ON tasks
FOR EACH ROW
EXECUTE FUNCTION task_updated_at();